execute if entity @s[advancements={cnk:cookbook/candy/item=true}] run data modify storage cnk:temp fizz.trading.items append value {loot_table:"cnk:food/candy/any_generic"}
execute if entity @s[advancements={cnk:cookbook/candy_cane/item=true}] run data modify storage cnk:temp fizz.trading.items append value {loot_table:"cnk:food/candy/cane"}
execute if entity @s[advancements={cnk:cookbook/candy_corn/item=true}] run data modify storage cnk:temp fizz.trading.items append value {loot_table:"cnk:food/candy/corn"}
execute if entity @s[advancements={cnk:cookbook/cinnamon/item=true}] run data modify storage cnk:temp fizz.trading.items append value {loot_table:"cnk:food/cinnamon"}
execute if entity @s[advancements={cnk:cookbook/dough/item=true}] run data modify storage cnk:temp fizz.trading.items append value {loot_table:"cnk:food/dough"}
execute if entity @s[advancements={cnk:cookbook/festive_cookie/item=true}] run data modify storage cnk:temp fizz.trading.items append value {loot_table:"cnk:food/festive_cookie/any"}
execute if entity @s[advancements={cnk:cookbook/frozen_delight/item=true}] run data modify storage cnk:temp fizz.trading.items append value {loot_table:"cnk:food/frozen_delight/any"}
execute if entity @s[advancements={cnk:cookbook/gingerbread/item=true}] run data modify storage cnk:temp fizz.trading.items append value {loot_table:"cnk:food/gingerbread/any"}
execute if entity @s[advancements={cnk:cookbook/golden_oldie/item=true}] run data modify storage cnk:temp fizz.trading.items append value {loot_table:"cnk:food/candy/caramel"}
execute if entity @s[advancements={cnk:cookbook/marshmallow/item=true}] run data modify storage cnk:temp fizz.trading.items append value {loot_table:"cnk:food/marshmallow/normal"}
execute if entity @s[advancements={cnk:cookbook/sundae/item=true}] run data modify storage cnk:temp fizz.trading.items append value {loot_table:"cnk:food/sundae"}

# code below is generated by beet