execute if entity @s[advancements={cnk:cookbook/candy/item=true}] run data modify storage cnk:temp fizz.trading.items append value {loot_table:"cnk:food/candy/any_generic", count:3}
execute if entity @s[advancements={cnk:cookbook/candy_cane/item=true}] run data modify storage cnk:temp fizz.trading.items append value {loot_table:"cnk:food/candy/cane", count:3}
execute if entity @s[advancements={cnk:cookbook/candy_corn/item=true}] run data modify storage cnk:temp fizz.trading.items append value {loot_table:"cnk:food/candy/corn", count:3}
execute if entity @s[advancements={cnk:cookbook/festive_cookie/item=true}] run data modify storage cnk:temp fizz.trading.items append value {loot_table:"cnk:food/festive_cookie/any", count:3}
execute if entity @s[advancements={cnk:cookbook/frozen_delight/item=true}] run data modify storage cnk:temp fizz.trading.items append value {loot_table:"cnk:food/frozen_delight/any", count:3}
execute if entity @s[advancements={cnk:cookbook/gingerbread/item=true}] run data modify storage cnk:temp fizz.trading.items append value {loot_table:"cnk:food/gingerbread/any", count:3}
execute if entity @s[advancements={cnk:cookbook/golden_oldie/item=true}] run data modify storage cnk:temp fizz.trading.items append value {loot_table:"cnk:food/candy/caramel", count:3}
execute if entity @s[advancements={cnk:cookbook/marshmallow/item=true}] run data modify storage cnk:temp fizz.trading.items append value {loot_table:"cnk:food/marshmallow/normal", count:3}
execute if entity @s[advancements={cnk:cookbook/sundae/item=true}] run data modify storage cnk:temp fizz.trading.items append value {loot_table:"cnk:food/sundae", count:3}

# code below is generated by beet