execute \
        if data storage cnk:temp cooking_pot.Items[{components:{"minecraft:custom_data":{cnk:{ingredient:{type:"dough",extra:"sourdough"}}}}}] \
        if function cnk:cooking_pot/crafting/lock \
        run return run function cnk:recipes/cooking_pot/sourdough_bread

execute \
        if entity @s[tag=cnk.witch_cauldron] \
        if data storage cnk:temp cooking_pot.Items[{components:{"minecraft:custom_data":{cnk:{disc:{type:"scarecrow"}}}}}] \
        if function cnk:cooking_pot/crafting/lock \
        run return run function cnk:recipes/cooking_pot/music_disc_trick

execute \
        if entity @s[tag=cnk.stove,tag=!cnk.panless_stove] \
        if data storage cnk:temp cooking_pot.Items[{id:"minecraft:tnt"}] \
        if function cnk:cooking_pot/crafting/lock \
        run return run function cnk:recipes/cooking_pot/pan

# code below is generated by beet