execute \
        if data storage cnk:temp cooking_pot.Items[{components:{"minecraft:custom_data":{cnk:{ingredient:{type:"dough"}}}}}] \
        if data storage cnk:temp cooking_pot.Items[{id:"minecraft:tnt"}] \
        if data storage cnk:temp cooking_pot.Items[{id:"minecraft:apple"}] \
        if data storage cnk:temp cooking_pot.Items[{id:"minecraft:sugar"}] \
        if function cnk:cooking_pot/crafting/lock \
        run return run function cnk:recipes/cooking_pot/psys_explosive_apple_pie

# code below is generated by beet