data_pack:
  load: .
  overlays:
    - directory: overlay_94_1
      min_format: [94,1]
      max_format: [94,1]
    - directory: overlay_101_1
      min_format: [94,1]
      max_format: [101,1]
  min_format: [94,1]
  max_format: [107,1]
  pack_format: 107

resource_pack:
  load: .
  min_format: [75,0]
  max_format: [88,0]
  pack_format: 88

require:
  - cnk.plugins.recipes.load_recipes

pipeline:
  - cnk.plugins.recipes
  - cnk.plugins.overlays.init
  - mecha
  - cnk.plugins.overlays.apply

output: .build

"description": [
  {"text":"\ud83c\udf56 Crop & Kettle \ud83c\udf56", "color":"#f9b560"},
  {"text":"\n"},
  {"text":"A cozy cooking datapack","color":"#7e7e7e"}
]