data_pack:
  load: .

resource_pack:
  load:
    - .

require:
  - cnk.plugins.recipes.load_recipes

pipeline:
  - cnk.plugins.recipes
  - cnk.plugins.release

version: 1.2.11
name: CropAndKettle