execute if entity @p[tag=cnk.interact_cutting_board,predicate=cnk:ritual_dagger,distance=..20] if data storage cnk:temp cutting_board.item{components:{"minecraft:custom_data":{cnk:{ingredient:{type:"mystery_meat"}}}}} run return run function cnk:recipes/cutting_board/meat_guide

# code below is generated by beet